In [39]:
import numpy as np
import matplotlib.pyplot as plt
import os
import joblib
import pandas as pd
from matplotlib.colors import ListedColormap

In [23]:
class Perceptron:
    def __init__(self, eta: float = None, epochs: int = None):
        self.weights = np.random.randn(3) * 1e-4
        training = (eta is not None) and (epochs is not None)
        if training:
            print(f"initial weights before training: \n{self.weights}")
            self.eta = eta
            self.epochs = epochs
    
    def _z_outcome(self, inputs, weights):
        return np.dot(inputs, weights)

    def activation_function(self,z):
        return np.where(z > 0, 1, 0)

    def fit(self, X, y):
        self.X = X
        self.y = y
        X_with_bias = np.c_[self.X, -np.ones((len(self.X),1))]  # doing a concatenation operation
        print("X with bias: \n{X_with_bias}")

        for epoch in range(self.epochs):
            print("--"*10)
            print(f"for epoch >> {epoch}")
            print("--"*10)
            
            z = self._z_outcome(X_with_bias, self.weights)
            y_hat = self.activation_function(z)
            print(f"predicted value after forward pass: \n{y_hat}")
            
            self.error = self.y - y_hat
            print(f"error: \n{self.error}")
            
            self.weights = self.weights + self.eta * np.dot(X_with_bias.T, self.error)
            print(f"updated weights after epoch: {epoch + 1}/{self.epochs}: \n{self.weights}")
            print("--"*10)

    def predict(self, X):
        X_with_bias = np.c_[X, -np.ones((len(X),1))]
        z = self._z_outcome(X_with_bias, self.weights)
        return self.activation_function(z)


    def total_loss(self):
        total_loss = np.sum(self.error)
        print(f"\ntotal loss: {total_loss}\n")
        return total_loss

    def _create_dir_return_path(self, model_dir, filename):
        os.makedirs(model_dir, exist_ok=True)
        return os.path.join(model_dir, filename)


    def save(self, filename, model_dir = None):
        if model_dir is not None:
            model_file_path = self._create_dir_return_path(model_dir, filename)
            joblib.dump(self, model_file_path)
        else:
            model_file_path = self._create_dir_return_path("model", filename)
            joblib.dump(self, model_file_path)

    def load(self, filepath):
        return joblib.load(filepath)


In [24]:
def prepare_data(df, target_column = "y"):
    X = df.drop("y", axis = 1)
    y = df["y"]
    return X, y

In [25]:
AND = {
    'x1' : [0,0,1,1],
    'x2' : [0,1,0,1],
    'y'  : [0,0,0,1]
}

df_AND = pd.DataFrame(AND)
print(df_AND)

   x1  x2  y
0   0   0  0
1   0   1  0
2   1   0  0
3   1   1  1


In [26]:
X, y  = prepare_data(df_AND)

ETA = 0.1
EPOCHS = 10

model_and = Perceptron(eta = ETA, epochs = EPOCHS)
model_and.fit(X,y)

_ = model_and.total_loss()  # _ denotes that it is a dummy value

initial weights before training: 
[ 6.10721643e-05  1.95827790e-04 -2.29164768e-04]
X with bias: 
{X_with_bias}
--------------------
for epoch >> 0
--------------------
predicted value after forward pass: 
[1 1 1 1]
error: 
0   -1
1   -1
2   -1
3    0
Name: y, dtype: int64
updated weights after epoch: 1/10: 
[-0.09993893 -0.09980417  0.29977084]
--------------------
--------------------
for epoch >> 1
--------------------
predicted value after forward pass: 
[0 0 0 0]
error: 
0    0
1    0
2    0
3    1
Name: y, dtype: int64
updated weights after epoch: 2/10: 
[6.10721643e-05 1.95827790e-04 1.99770835e-01]
--------------------
--------------------
for epoch >> 2
--------------------
predicted value after forward pass: 
[0 0 0 0]
error: 
0    0
1    0
2    0
3    1
Name: y, dtype: int64
updated weights after epoch: 3/10: 
[0.10006107 0.10019583 0.09977084]
--------------------
--------------------
for epoch >> 3
--------------------
predicted value after forward pass: 
[0 1 1 1]
error: 

In [27]:
model_and.save(filename="and.model")

In [32]:
reload_model_and = Perceptron().load(filepath= r'C:\Users\USER\Desktop\Project\Learn-Implement-Predict\model\and.model')

In [34]:
reload_model_and.predict(X = [[1,1]])

array([1])

In [28]:
OR = {
    'x1' : [0,0,1,1],
    'x2' : [0,1,0,1],
    'y'  : [0,1,1,1]
}

df_OR = pd.DataFrame(OR)
print(df_OR)

   x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  1


In [29]:
X, y  = prepare_data(df_OR)

ETA = 0.1
EPOCHS = 10

model_or = Perceptron(eta = ETA, epochs = EPOCHS)
model_or.fit(X,y)

_ = model_or.total_loss()

initial weights before training: 
[ 8.17407602e-05 -1.32002297e-04 -2.17591682e-05]
X with bias: 
{X_with_bias}
--------------------
for epoch >> 0
--------------------
predicted value after forward pass: 
[1 0 1 0]
error: 
0   -1
1    1
2    0
3    1
Name: y, dtype: int64
updated weights after epoch: 1/10: 
[ 0.10008174  0.199868   -0.10002176]
--------------------
--------------------
for epoch >> 1
--------------------
predicted value after forward pass: 
[1 1 1 1]
error: 
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updated weights after epoch: 2/10: 
[ 1.00081741e-01  1.99867998e-01 -2.17591682e-05]
--------------------
--------------------
for epoch >> 2
--------------------
predicted value after forward pass: 
[1 1 1 1]
error: 
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updated weights after epoch: 3/10: 
[0.10008174 0.199868   0.09997824]
--------------------
--------------------
for epoch >> 3
--------------------
predicted value after forward pass: 
[0 1 1 1]
erro

In [35]:
model_or.save(filename = "or.model")

In [36]:
model_or.predict(X = [[0,1]])

array([1])

In [37]:
reload_model_or = Perceptron().load(filepath= r'C:\Users\USER\Desktop\Project\Learn-Implement-Predict\model\or.model')

In [38]:
model_or.predict(X = [[0,0]])

array([0])

In [30]:
XOR = {
    'x1' : [0,0,1,1],
    'x2' : [0,1,0,1],
    'y'  : [0,1,1,0]
}

df_XOR = pd.DataFrame(XOR)
print(df_XOR)

   x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  0


In [31]:
X, y  = prepare_data(df_XOR)

ETA = 0.1
EPOCHS = 10

model_xor = Perceptron(eta = ETA, epochs = EPOCHS)
model_xor.fit(X,y)

_ = model_xor.total_loss()

initial weights before training: 
[ 2.02633550e-05  8.30239831e-05 -6.24136183e-05]
X with bias: 
{X_with_bias}
--------------------
for epoch >> 0
--------------------
predicted value after forward pass: 
[1 1 1 1]
error: 
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
updated weights after epoch: 1/10: 
[-0.09997974 -0.09991698  0.19993759]
--------------------
--------------------
for epoch >> 1
--------------------
predicted value after forward pass: 
[0 0 0 0]
error: 
0    0
1    1
2    1
3    0
Name: y, dtype: int64
updated weights after epoch: 2/10: 
[ 2.02633550e-05  8.30239831e-05 -6.24136183e-05]
--------------------
--------------------
for epoch >> 2
--------------------
predicted value after forward pass: 
[1 1 1 1]
error: 
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
updated weights after epoch: 3/10: 
[-0.09997974 -0.09991698  0.19993759]
--------------------
--------------------
for epoch >> 3
--------------------
predicted value after forward pass: 
[0 0 0 0]
e

A single perceptron is a linear classifier. It can't classify non-linear data.

In [40]:
def save_plot(df, model, filename = "plot.png", plot_dir = "plots"):

    def _create_base_plot(df):
        df.plot(kind = "scatter", x = "x1", y = "x2", c = "y", s = 100, cmap = "coolwarm")
        plt.axhline(y = 0, color = "black", linestyle = "--", linewidth = 1)
        plt.axvline(x = 0, color = "black", linestyle = "--", linewidth = 1)

        figure = plt.gcf()
        figure.set_size_inches(10, 8)

    def _plot_decision_regressions(X, y, classifier, resolution = 0.02):
        colors = ("cyan",  "lightgreen")
        cmap = ListedColorMap(colors)
        X = X.values
        x1 = X[:, 0]
        x2 = X[:, 1]

        x1_min, x1_max = x1.min() - 1, x1.max() + 1
        x2_min, x2_max = x2.min() - 1, x2.max() + 1

        xx1, xx2 = np.meshgrid(np.arange(x1_min, x1_max, resolution),
                            np.arange(x2_min, x2_max, resolution)
                            ) 

        y_hat = classifier.predict(np.array([xx1.ravel(), xx2.ravel()]).T)  # ravel() flattens the array
        y_hat = y_hat.reshape(xx1.shape)
        plt.contourf(xx1, xx2, y_hat, alpha = 0.2, cmap = cmap)
        plt.xlim(xx1.min(), xx1.max())
        plt.ylim(xx2.min(), xx2.max())

        plt.plot()

    X, y = prepare_data(df)

    _create_base_plot(df)
    _plot_decision_regressions(X, y, model)

    os.makedirs(plot_dir, exist_ok=True)
    plot_path = os.path.join(plot_dir, filename)
    plt.savefig(plot_path)

In [ ]:
save_plot(df_OR, model_or, filename = "or.png")